/// The compilation condition that guards a mock generated by ``Mockable(condition:)``.
///
/// By default, generated mocks are wrapped in `#if DEBUG` so they never ship in
/// release builds. Pass a different condition to `@Mockable` when a mock must be
/// available elsewhere — for example in a test-support module that is built in the
/// release configuration, in SwiftUI previews, or in a UI-test host app:
///
/// ```swift
/// @Mockable                                    // #if DEBUG (default)
/// protocol UserService { ... }
///
/// @Mockable(condition: .custom("MOCKING"))     // #if MOCKING
/// protocol PaymentService { ... }
///
/// @Mockable(condition: .always)                // no #if guard
/// protocol PreviewDataService { ... }
/// ```
///
/// The condition must be written literally at the attachment site (`.debug`,
/// `.always`, or `.custom("FLAG")` with a string literal) — the macro expands at
/// compile time and cannot read runtime values.
public enum MockCompilationCondition: Equatable, Sendable {
    /// Wraps the generated mock in `#if DEBUG`. This is the default.
    case debug

    /// Emits the generated mock unconditionally, with no `#if` guard.
    ///
    /// The mock is then part of every build configuration, including release
    /// builds. Use this deliberately — for example in a dedicated test-support
    /// module that is never linked into a shipping product.
    case always

    /// Wraps the generated mock in `#if` with a custom compilation condition.
    ///
    /// The associated value must be a compilation condition expression, spelled
    /// as a string literal — a flag such as `"MOCKING"`, or a compound condition
    /// built from identifiers, `true`/`false`, `!`, `&&`, `||`, parentheses, and
    /// platform checks:
    ///
    /// ```swift
    /// @Mockable(condition: .custom("MOCKING"))
    /// @Mockable(condition: .custom("DEBUG || UITESTS"))
    /// @Mockable(condition: .custom("os(iOS) && !RELEASE"))
    /// ```
    ///
    /// Define each flag in the build settings of every target that needs the
    /// mock — via `SWIFT_ACTIVE_COMPILATION_CONDITIONS` in Xcode, or
    /// `.define("MOCKING")` in a package manifest's `swiftSettings`.
    case custom(String)
}
